server:
  port: 9003


spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        #换成nginx的1111端口，做集群
        server-addr: 192.168.3.9:1111


management:
  endpoints:
    web:
      exposure:
        include: '*'
