server:
  port: 83

spring:
  application:
    name: cloud-consumer-feign-order

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # 单机版
      # defaultZone: http://localhost:7001/eureka
      #集群版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: consumer83  #修改显示的主机名
    prefer-ip-address: true   #访问路径可以显示ip地址

#没提示不管它，可以设置
ribbon:
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ReadTimeout: 5000
  #指的是建立连接使用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ConnectTimeout: 5000

logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.atguigu.springcloud.service.PaymentFeignService: debug
